# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_30; PHPUNIT=5.7.*
      php: 7.0
    - env: DB=mysql; MW=REL1_27; TYPE=coverage
      php: 5.6
    - env: DB=sqlite; MW=REL1_27;
      php: 5.6
    - env: DB=mysql; MW=master; PHPUNIT=4.8.*
      php: hhvm

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-data-import.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
